### ISSUE TITLE
API kvar efter att användare raderats

### ISSUE THREAD

**Issue by AndreasBom** [ks222rt/1DV450_ks222rt#1]
När jag raderar en användare som har API-nycklar, raderas användaren från databasen, men dennes API-nycklar finns kvar. Man kan anta att om användaren försvinner ska även alla nycklarna försvinna.

Det du behöver är refrenciell integriditet(?)(På engelska: Referential Integrity Constraints) i databasen. 

I users-klassen där man deklarerar:
has_many :api 
kan man lägga till :dependent => :delete_all    d.v.s: 
has_many :api, :dependent => :delete_all

**Comment by ks222rt** [comment]
Ah hade jag missat det! Tack för feedbacken, ska föra in det i systemet!

Den 8 februari 2016 15:31 skrev Andreas Bom <notifications@github.com>:

**Comment by 1dv450** [comment]
Bra. Gå igenom issues och stäng issuen när den är klar

**Comment by ks222rt** [comment]
Har ändrat detta så keys tas bort med en användare
