### ISSUE TITLE
Peer review #3 - Tomt flashmeddelande vid uppdatering av pub

### ISSUE THREAD

**Issue by kk222hk** [ks222rt/1DV450_ks222rt#10]
Prövade att editera en pub när jag var inloggad med kontot "stoffe", och fick ett skumt resultat. Om jag går in på en pub, ändrar något värde och trycker "Update pub" så får jag ett tomt rött flashmeddelande.

![http://i.imgur.com/Br9VXoA.png](http://i.imgur.com/Br9VXoA.png)

Puben uppdateras dock ändå så det är ju inte hela världen.

**Comment by ks222rt** [comment]
Har inte lagt till någon större ändring men när jag uppdaterar en pub så får jag ett grönt meddelande med "Event updated".
![nlos](https://cloud.githubusercontent.com/assets/8626494/13920857/5df67fb2-ef75-11e5-9aa9-60ae83697282.png)

**Comment by kk222hk** [comment]
Prövade igen och då blev det grönt med event updated för mig med. Verkar som att det var någon engångsgrej :beers:
