### ISSUE TITLE
Peer review #3 - Validering av pubar

### ISSUE THREAD

**Issue by kk222hk** [ks222rt/1DV450_ks222rt#11]
Märkte att jag kan skapa pubar med vilka värden som helst. Framförallt zip code kanske borde valideras med ett reguljärt uttryck, så att det är på rätt format.

Maxlängd kan också vara bra att validera.

Jag hade nog validerat det både i API't och på klienten.

**Comment by ks222rt** [comment]
Har lagt till validering på uppdate och add formulären. Maxlenght och zip code bland annat.
