### ISSUE TITLE
Peer review #3 - Sortera efter alla taggar

### ISSUE THREAD

**Issue by kk222hk** [ks222rt/1DV450_ks222rt#12]
När man har valt en tagg att sortera efter, vore det nice att kunna välja att sortera efter alla taggar igen. Nu måste man ladda om sidan för att återställa den sorteringen.

Ett förslag på hur man skulle kunna lösa det. [Select-menyn som väljer tagg](https://github.com/ks222rt/1DV450_ks222rt/blob/master/SPA/app/components/home/home.html#L16-L18) har du kopplat med ng-click till [en funktion på $rootScope i app_routes.js](https://github.com/ks222rt/1DV450_ks222rt/blob/master/SPA/app/app_routes.js#L97-L99). 

Om du istället har koden för den funktionen i en controller, har du tillgång till det scope som har "SelectedTag" som selecttaggen sätter via ng-model. 

Då kan du kolla om $scope.SelectedTag är null, och isåfall hämta alla pubar. Då behöver du inte heller skicka med SelectedTag som parameter i ng-click. Och som bonus blir du mindre beroende av $rootScope.

**Comment by ks222rt** [comment]
Gjorde så att om man väljer "Sort on tags" i select rutan så skall man sortera på alla tags igen, alltså startsidan. Dock fungerar det ibland och ibland inte av någon anledning.. så har lagt dit en extra knapp för att "säkra" upp denna lösning. Inget snyggt gjort men det fungerar
