### ISSUE TITLE
Peer review #3 - Kod på $rootScope i routes-filen

### ISSUE THREAD

**Issue by kk222hk** [ks222rt/1DV450_ks222rt#13]
[Denna kod](https://github.com/ks222rt/1DV450_ks222rt/blob/master/SPA/app/app_routes.js#L97-L105) känns lite felplacerad. 

När man använder $rootScope mycket så kan det bli svårt att hålla koll på vad som påverkar vad i applikationen. app_routes.js känns inte heller som en logisk plats att ha funktioner för att sortera saker på. Det tog ett tag innan jag hittade koden som sorterar taggar, då jag letade i dina controllers först.

Jag hade nog använt app_routes.js enbart till att ställa in states, och flyttat ut denna kod till en controller.

**Comment by ks222rt** [comment]
De 2 funktionerna i $rootScope är utflyttade till 2 controllers nu
