### ISSUE TITLE
Peer review #3 - Access control för pubar

### ISSUE THREAD

**Issue by kk222hk** [ks222rt/1DV450_ks222rt#14]
Man kan som oinloggad användare komma åt formulären för att ändra och lägga till pubar, genom att skriva in respektive URL och trycka enter. Exempelvis /edit_pub/5/ eller /add_pub/.

När man försöker posta formuläret händer ingenting i gränssnittet men man får detta i konsollen:

![http://i.imgur.com/rS5Gp9g.png](http://i.imgur.com/rS5Gp9g.png)

Det kan vara bra att skydda olika states så att man blir redirectad tillbaka till start om man inte är inloggad. [Så här löste jag det](https://github.com/kk222hk/1DV450_kk222hk/blob/master/client/app.states.js#L48-L55), så att jag kan definiera authenticate: false eller true för varje state.

**Comment by ks222rt** [comment]
Såg din lösning och den fungerade grymt bra. Så nu är det löst.
