### ISSUE TITLE
Peer review #3 - Allmänt

### ISSUE THREAD

**Issue by kk222hk** [ks222rt/1DV450_ks222rt#15]
Hej! Nu har jag kollat igenom din applikation och här är lite allmän feedback.

**Installation**
Det var inga större problem att få igång applikationen. Först fungerade ingenting och jag fick en 401 Unauthorized i konsollen. Kom på att det berodde på att API-nyckeln var fel då dessa slumpas fram när man kör seedsfilen i API't, så jag fick gå in i app_routes.js och ändrade värdet för konstanten. Det kan vara bra att nämna det in installationsbeskrivningen.

**Funktionalitet**
Har gått igenom all funktionalitet som applikationen ska ha, och allting fungerar. Det finns en del extra funktionalitet dessutom, som möjlighet att lägga till taggar när man skapar events.

Märkte att flashmeddelandena ibland inte dyker upp på rätt sätt. Se separat issue för det.

**Design**
Tycker att designen funkar bra. Enkelt och stilrent. Kartan kunde kanske varit lite större på höjden.

Snygg lösning i listan med pubar, när man klickar på en pub och alla detaljer visas.

Den responsiva designen fungerar också. Formulär hamnar dock en bit till vänster om andra element när man minskar storleken på browsern.

**Kod**
Bra att du tänkt i komponenter när du delat upp din kod. Det gjorde det lättare för mig att hitta var koden för olika saker var, och förstå hur du tänkt när du delat upp applikationen.

Det finns lite död kod (utkommenterad) här och där, i HomeController tex. Det finns knappt några kommentarer, men du har döpt saker bra så det går att lista ut vad funktioner gör ändå.

I övrigt ser koden bra ut. Konsekvent indentering, logisk namngivning som sagt.

**Förbättringsförslag**
Jag har några förslag på saker som kan fixas, har gjort en issue var varje förslag.

**Sammanfattning**
Bra jobbat! :beers:

**Comment by ks222rt** [comment]
Tack, grym feedback!
