### ISSUE TITLE
Ingen roll

### ISSUE THREAD

**Issue by AndreasBom** [ks222rt/1DV450_ks222rt#2]
Du har egentligen inte tilldelat admin en roll, utan för att få admin-rättigheter, så frågar du om användarnamnet är 'admin' (vilket inte är riktigt samma sak som att tilldela en roll). 

Detta funkar ju om man enbart kommer ha 1 admin och inte ha flera olika roller. 

Att tilldela roller till olika användare kan göras på olika sätt, men det enklaste kanske är att skapa en egenskap i users-modellen som heter 'role'. Är den tom är användaren inte admin, om användaren är admin, skrivs detta i roleegenskapen. 

Vill man göra det mer flexibelt skapar man en klass som innehåller egenskaperna:
ID
Role

och tilldelar man värden skulle det kunna se ut så här;
ID: 1
Role: 'admin'

ID: 2
Role: 'basicUser'

i en relationstabel kopplar man ihop role med user
RoleID 
1    
userID
23

Nu har användaren med id 23 tilldelats rollen admin (RoleId 1)

**Comment by ks222rt** [comment]
Har ändrat så att en "användare" kan ha en roll som t.ex. admin.
