### ISSUE TITLE
Global protect_from_forgery with: :null_session

### ISSUE THREAD

**Issue by rk222ev** [ks222rt/1DV450_ks222rt#6]
Setting  protect_from_forgery with: :null_session in the ApplicationController will enforce this behaviour on the entire app. Apikey registration and admin features included.

I don't know if this is the intended and expected behaviour. But an alternative solution would be to move the null_session to a BaseController that inherits from ApplicationController and then let the different api controllers inherit from BaseController. Keeping the option protect_from_forgery in controllers inheriting directly from ApplicationController.

For more info on the different options see:
http://stackoverflow.com/a/31236249/4248654

Just a thought.

**Comment by ks222rt** [comment]
Done. Made a basecontroller in the api who inherits from applicationcontroller.
